### ISSUE TITLE
Running SharedKafkaTestResourceTest in a loop causes errors

### ISSUE THREAD

**Issue by hi2karthik** [salesforce/kafka-junit#16]
When I run SharedKafkaTestResourceTest in loop - say 5 times (from IntelliJ IDE - By setting the Repeat setting to 5), the second run fails to start with the following Kafka error "Connection to node -2 could not be established. Broker may not be available"

[kafka-junit-error.txt](https://github.com/salesforce/kafka-junit/files/2082484/kafka-junit-error.txt)

**Comment by Crim** [comment]
Sorry for the delayed response.  Which version of the library are you using?  Can you post a slimmed down example test class showing how its being setup and used?

Thanks!

**Comment by Crim** [comment]
Ah I see the issue.  I'll put together a patch here shortly to resolve it.

**Comment by Crim** [comment]
I just released 3.0.1.  It should resolve this issue for you.  If you continue to have issues please let me know.

Thanks!

**Comment by hi2karthik** [comment]
@Crim - How often do you publish the version to maven-central?
I dont see 3.0.1 on https://oss.sonatype.org/content/repositories/releases/com/salesforce/kafka/test/kafka-junit4/

**Comment by Crim** [comment]
Hmm the deploy process must not have actually completed.  I'll push it up once I get into the office in a couple hours.

**Comment by Crim** [comment]
Appologies, published it just now, should be available: https://oss.sonatype.org/content/repositories/releases/com/salesforce/kafka/test/kafka-junit4/3.0.1/

**Comment by hi2karthik** [comment]
@Crim - thanks a lot.
