### ISSUE TITLE
Compatibility betweekn kafka-junit and Kafka-streams

### ISSUE THREAD

**Issue by SimoneCas** [salesforce/kafka-junit#19]
I have developed a kafka-streams application and I'm using kafka-junit4 to test my application.
With the SharedKafkaTestResource class I can use Kafka Consumer and Kafka Producer while my kafka streams app don't link to the sharedKafkaTestResource.

Does sharedKafkaTestResource support KafkaStream?

What is the KafkaStream configuration to connect it to the in memory Kafka Cluster?

The following code snippet shows how I connect my kafkaStream to the SharedKafkaTestResource:
`
@ClassRule
	public static final SharedKafkaTestResource sharedKafkaTestResource = new SharedKafkaTestResource();

final KafkaTestUtils kafkaTestUtils = getKafkaTestUtils();
		kafkaTestUtils.createTopic(INPUT_TOPIC, 5, Short.valueOf("1"));
		kafkaTestUtils.createTopic(OUTPUT_TOPIC, 5, Short.valueOf("1"));

Properties props = new Properties();
		props.setProperty(StreamsConfig.APPLICATION_ID_CONFIG, "registryStreamProcessor");
		props.setProperty(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, sharedKafkaTestResource.getKafkaConnectString());
		RegistryKafkaStream stream = new RegistryKafkaStream(props, INPUT_TOPIC, OUTPUT_TOPIC, Consumed.with(new AdapterMessageKeySerde(), new Serdes.StringSerde()));
		stream.start();`

**Comment by Crim** [comment]
I'm not super familiar w/ KafkaStreams, but from reading the code you posted, the RegistryKafkaStream instance should be configured to talk to the internal kafka service.

Are you getting any errors?

**Comment by SimoneCas** [comment]
The following code is my complete class.
In my class I follow this order:
1 - I define SharedKafkaTestResource
2 - I extract a KafkaTestUtils instance and I create two topics
3 - I produce four messages on the input topic
4 - I configure and start my kafka streams application
5 - I monitor the messages on the output topic

**Do you confirm me the compatibility between kafka-junit and kafka-streams applications?** 



`import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import java.util.Properties;

import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.common.serialization.StringSerializer;
import org.apache.kafka.streams.Consumed;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.test.ConsumerRecordFactory;
import org.junit.Assert;
import org.junit.ClassRule;
import org.junit.Ignore;
import org.junit.Test;

import com.salesforce.kafka.test.KafkaTestUtils;
import com.salesforce.kafka.test.junit4.SharedKafkaTestResource;

import it.sisal.betting.bo.messaging.common.util.FileUtil;
import it.sisal.betting.bo.messaging.kafka.deserializer.EventValueRegistryDTODeserializer;
import it.sisal.betting.bo.messaging.kafka.deserializer.RegistryMessageKeyDeserializer;
import it.sisal.betting.bo.messaging.kafka.serde.AdapterMessageKeySerde;
import it.sisal.betting.bo.messaging.kafka.serializer.AdapterMessageKeySerializer;
import it.sisal.betting.bo.messaging.model.kafka.AdapterMessageKey;
import it.sisal.betting.bo.messaging.model.kafka.RegistryMessageKey;
import it.sisal.betting.bo.model.messaging.registry.dto.output.EventKeyDTO;
import it.sisal.betting.bo.model.messaging.registry.dto.output.EventValueDTO;
import it.sisal.betting.commons.messaging.kafka.producer.KafkaProviderProducer;

public class RegistryKafkaStreamTest3 {

	private static final String INPUT_TOPIC = "InputBettingOfferTopic";
	private static final String OUTPUT_EVENT_TOPIC = "EventsRegistryTopic";
	private static final String OUTPUT_MARKET_TOPIC = "MarketsRegistryTopic";

	private ConsumerRecordFactory<AdapterMessageKey, String> recordFactory = new ConsumerRecordFactory<>(INPUT_TOPIC,
			new AdapterMessageKeySerializer(), new StringSerializer());

	private KafkaProviderProducer<AdapterMessageKey, String> kafkaProviderProducer;
	private Properties properties = new Properties();

	@ClassRule
	public static final SharedKafkaTestResource sharedKafkaTestResource = new SharedKafkaTestResource();

	private KafkaTestUtils getKafkaTestUtils() {
		return sharedKafkaTestResource.getKafkaTestUtils();
	}

	@Test
	public void testOneEntry() throws Exception {
		String filename = "ivt/ivt1.xml";
		Instant nowInstant = Instant.now();
		AdapterMessageKey key = new AdapterMessageKey();
		key.setEventId(1043);
		key.setEventVariationTimestamp(nowInstant);
		key.setForwardTimestamp(nowInstant);
		key.setReceiptTimestamp(nowInstant);
		key.setRequestID("requestId1");

		String value = FileUtil.getFile(filename);

		this.kafkaProviderProducer = getKafkaProviderProducer();
		
		final KafkaTestUtils kafkaTestUtils = getKafkaTestUtils();
		kafkaTestUtils.createTopic(INPUT_TOPIC, 5, Short.valueOf("1"));
		kafkaTestUtils.createTopic(OUTPUT_EVENT_TOPIC, 5, Short.valueOf("1"));
		kafkaTestUtils.createTopic(OUTPUT_MARKET_TOPIC, 5, Short.valueOf("1"));
		
		this.kafkaProviderProducer.send(key, value);
		this.kafkaProviderProducer.send(key, value);
		this.kafkaProviderProducer.send(key, value);
		this.kafkaProviderProducer.send(key, value);
		
		Properties props = new Properties();
		props.setProperty(StreamsConfig.APPLICATION_ID_CONFIG, "registryStreamProcessor");
		props.setProperty(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, sharedKafkaTestResource.getKafkaConnectString());
		RegistryKafkaStream stream = new RegistryKafkaStream(props, INPUT_TOPIC, OUTPUT_EVENT_TOPIC, OUTPUT_MARKET_TOPIC, Consumed.with(new AdapterMessageKeySerde(), new Serdes.StringSerde()));
		stream.start();
		
		RegistryMessageKey expectedKey = new RegistryMessageKey();
		expectedKey.setEventId(1043);
		expectedKey.setEventVariationTimestamp(nowInstant);
		expectedKey.setForwardTimestamp(nowInstant);
		expectedKey.setReceiptTimestamp(nowInstant);
		expectedKey.setRequestID("requestId1");

		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
		Date date = sdf.parse("2016-07-31 01:59:00.000");

		EventValueDTO expectedValue = new EventValueDTO();
		expectedValue.setCompetitionId(214);
		expectedValue.setDescription("Millonarios - Rionegro Aguilas");
		expectedValue.setEventDate(date);
		expectedValue.setEventKeyDTO(new EventKeyDTO(1043l));
		expectedValue.setSportId(1);

		 final List<ConsumerRecord<RegistryMessageKey, EventValueDTO>> consumerRecords
         = kafkaTestUtils.consumeAllRecordsFromTopic(OUTPUT_EVENT_TOPIC, RegistryMessageKeyDeserializer.class, EventValueRegistryDTODeserializer.class);
		 Assert.assertNotNull(consumerRecords);
	     Assert.assertEquals(1, consumerRecords.size());
	     
	     Assert.assertEquals(expectedKey, consumerRecords.get(0).key());
	     Assert.assertEquals(expectedValue, consumerRecords.get(0).value());
	}

	private KafkaProviderProducer<AdapterMessageKey, String> getKafkaProviderProducer() throws Exception  {
        try
        {
        	Properties properties = getKafkaProperties();
            Properties kafkaProperties = new Properties();
            properties.keySet()
                    .stream()
                    //.filter(key -> ((String) key).startsWith(Keys.KAFKA_PREFIX))
                    .forEach(key -> kafkaProperties.put(
                            ((String) key).replace("kafka.", ""),
                            properties.get(key))
                    );
            System.out.println("kafkaProperties: " + kafkaProperties);
            kafkaProperties.setProperty("bootstrap.servers", this.sharedKafkaTestResource.getKafkaConnectString());
            return new KafkaProviderProducer<AdapterMessageKey, String>(
                    kafkaProperties, INPUT_TOPIC
            );
        }
        catch (Exception e) {
            throw new Exception("Unable to instantiate Kafka producer",e);
        }
    }

	private Properties getKafkaProperties() {
		Properties properties = new Properties();
		properties.put("kafka.acks", "all");
		properties.put("kafka.key.serializer", "it.sisal.betting.bo.messaging.kafka.serializer.AdapterMessageKeySerializer");
		properties.put("kafka.value.serializer", "org.apache.kafka.common.serialization.StringSerializer");
		properties.put("kafka.partitioner.class", "it.sisal.betting.bo.messaging.kafka.partitioner.FixtureProviderPartitioner");
		properties.put("kafka.retries", "0");
		properties.put("kafka.batch.size", "16384");
		properties.put("kafka.linger.ms", "1");
		properties.put("kafka.buffer.memory", "33554432");
		properties.put("bootstrap.servers", this.sharedKafkaTestResource.getKafkaConnectString());	
		properties.put(StreamsConfig.APPLICATION_ID_CONFIG, "registryStreamProcessor");
		return properties;
	}
}`

**_During the unit test I don't have error logs, but I found more times this exception logged in debug:_**

11:43:52.671 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-0] DEBUG o.a.kafka.common.network.Selector - [SocketServer brokerId=1] Connection with /127.0.0.1 disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:124)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:93)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:235)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:196)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:557)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:495)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:424)
	at kafka.network.Processor.poll(SocketServer.scala:628)
	at kafka.network.Processor.run(SocketServer.scala:545)
	at java.lang.Thread.run(Thread.java:748)

**_These are kafka logs from my application start: (registryStreamProcessor is my Streams Application)_**

11:47:10.679 [main] INFO  i.s.b.b.m.k.s.RegistryKafkaStream - Created stream KafkaStreams processID: 6bea4a36-c783-4d58-9c2b-b4a330e0b287
		StreamsThread threadId: registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1
		Active tasks:
			Running:
			Suspended:
			Restoring:
			New:
		Standby tasks:
			Running:
			Suspended:
			Restoring:
			New:


11:47:10.681 [main] DEBUG o.apache.kafka.streams.KafkaStreams - stream-client [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287] Starting Streams client
11:47:10.683 [main] INFO  o.apache.kafka.streams.KafkaStreams - stream-client [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287] Started Streams client
11:47:10.689 [main] INFO  o.a.k.c.admin.AdminClientConfig - AdminClientConfig values: 
	bootstrap.servers = [127.0.0.1:53587]
	client.id = test-consumer-id
	connections.max.idle.ms = 300000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 120000
	retries = 5
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

11:47:10.694 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name connections-closed:
11:47:10.694 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name connections-created:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name successful-authentication:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name failed-authentication:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name bytes-sent-received:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name bytes-sent:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name bytes-received:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name select-time:
11:47:10.695 [main] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name io-time:
11:47:10.696 [main] DEBUG org.apache.kafka.clients.Metadata - Updated cluster metadata version 1 to Cluster(id = null, nodes = [127.0.0.1:53587 (id: -1 rack: null)], partitions = [])
11:47:10.696 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version : 1.1.0
11:47:10.696 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId : fdcf75ea326b8e07
11:47:10.696 [main] DEBUG o.a.k.clients.admin.KafkaAdminClient - [AdminClient clientId=test-consumer-id] Kafka admin client initialized
11:47:10.697 [main] DEBUG o.a.k.clients.admin.KafkaAdminClient - [AdminClient clientId=test-consumer-id] Queueing Call(callName=describeTopics, deadlineMs=1533721750697) with a timeout 120000 ms from now.
11:47:10.699 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] INFO  o.a.k.s.p.internals.StreamThread - stream-thread [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] Starting
11:47:10.699 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] INFO  o.a.k.s.p.internals.StreamThread - stream-thread [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] State transition from CREATED to RUNNING
11:47:10.701 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.k.clients.consumer.KafkaConsumer - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Subscribed to pattern: InputBettingOfferTopic|registryStreamProcessor-KSTREAM-REDUCE-STATE-STORE-0000000005-repartition
11:47:10.702 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Sending FindCoordinator request to broker 127.0.0.1:53587 (id: -1 rack: null)
11:47:10.708 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Initiating connection to node 127.0.0.1:53587 (id: -1 rack: null)
11:47:10.709 [kafka-socket-acceptor-ListenerName(PLAINTEXT)-PLAINTEXT-53587] DEBUG kafka.network.Acceptor - Accepted connection from /127.0.0.1:53635 on /127.0.0.1:53587 and assigned it to processor 0, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400]
11:47:10.711 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-0] DEBUG kafka.network.Processor - Processor 0 listening to new connection from /127.0.0.1:53635
11:47:10.712 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name node--1.bytes-sent
11:47:10.712 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name node--1.bytes-received
11:47:10.713 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.kafka.common.metrics.Metrics - Added sensor with name node--1.latency
11:47:10.713 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.a.kafka.common.network.Selector - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Created socket with SO_RCVBUF = 65536, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -1
11:47:10.714 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Completed connection to node -1. Fetching API versions.
11:47:10.714 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Initiating API versions fetch from node -1.
11:47:10.715 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-0] DEBUG kafka.request.logger - Completed request:RequestHeader(apiKey=API_VERSIONS, apiVersion=1, clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, correlationId=1) -- {},response:{error_code=0,api_versions=[{api_key=0,min_version=0,max_version=5},{api_key=1,min_version=0,max_version=7},{api_key=2,min_version=0,max_version=2},{api_key=3,min_version=0,max_version=5},{api_key=4,min_version=0,max_version=1},{api_key=5,min_version=0,max_version=0},{api_key=6,min_version=0,max_version=4},{api_key=7,min_version=0,max_version=1},{api_key=8,min_version=0,max_version=3},{api_key=9,min_version=0,max_version=3},{api_key=10,min_version=0,max_version=1},{api_key=11,min_version=0,max_version=2},{api_key=12,min_version=0,max_version=1},{api_key=13,min_version=0,max_version=1},{api_key=14,min_version=0,max_version=1},{api_key=15,min_version=0,max_version=1},{api_key=16,min_version=0,max_version=1},{api_key=17,min_version=0,max_version=1},{api_key=18,min_version=0,max_version=1},{api_key=19,min_version=0,max_version=2},{api_key=20,min_version=0,max_version=1},{api_key=21,min_version=0,max_version=0},{api_key=22,min_version=0,max_version=0},{api_key=23,min_version=0,max_version=0},{api_key=24,min_version=0,max_version=0},{api_key=25,min_version=0,max_version=0},{api_key=26,min_version=0,max_version=0},{api_key=27,min_version=0,max_version=0},{api_key=28,min_version=0,max_version=0},{api_key=29,min_version=0,max_version=0},{api_key=30,min_version=0,max_version=0},{api_key=31,min_version=0,max_version=0},{api_key=32,min_version=0,max_version=1},{api_key=33,min_version=0,max_version=0},{api_key=34,min_version=0,max_version=0},{api_key=35,min_version=0,max_version=0},{api_key=36,min_version=0,max_version=0},{api_key=37,min_version=0,max_version=0},{api_key=38,min_version=0,max_version=0},{api_key=39,min_version=0,max_version=0},{api_key=40,min_version=0,max_version=0},{api_key=41,min_version=0,max_version=0},{api_key=42,min_version=0,max_version=0}],throttle_time_ms=0} from connection 127.0.0.1:53587-127.0.0.1:53635-6;totalTime:1.231,requestQueueTime:0.473,localTime:0.353,remoteTime:0.0,throttleTime:0.224,responseQueueTime:0.224,sendTime:0.181,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS,listener:PLAINTEXT
11:47:10.716 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Recorded API versions for node -1: (Produce(0): 0 to 5 [usable: 5], Fetch(1): 0 to 7 [usable: 7], ListOffsets(2): 0 to 2 [usable: 2], Metadata(3): 0 to 5 [usable: 5], LeaderAndIsr(4): 0 to 1 [usable: 1], StopReplica(5): 0 [usable: 0], UpdateMetadata(6): 0 to 4 [usable: 4], ControlledShutdown(7): 0 to 1 [usable: 1], OffsetCommit(8): 0 to 3 [usable: 3], OffsetFetch(9): 0 to 3 [usable: 3], FindCoordinator(10): 0 to 1 [usable: 1], JoinGroup(11): 0 to 2 [usable: 2], Heartbeat(12): 0 to 1 [usable: 1], LeaveGroup(13): 0 to 1 [usable: 1], SyncGroup(14): 0 to 1 [usable: 1], DescribeGroups(15): 0 to 1 [usable: 1], ListGroups(16): 0 to 1 [usable: 1], SaslHandshake(17): 0 to 1 [usable: 1], ApiVersions(18): 0 to 1 [usable: 1], CreateTopics(19): 0 to 2 [usable: 2], DeleteTopics(20): 0 to 1 [usable: 1], DeleteRecords(21): 0 [usable: 0], InitProducerId(22): 0 [usable: 0], OffsetForLeaderEpoch(23): 0 [usable: 0], AddPartitionsToTxn(24): 0 [usable: 0], AddOffsetsToTxn(25): 0 [usable: 0], EndTxn(26): 0 [usable: 0], WriteTxnMarkers(27): 0 [usable: 0], TxnOffsetCommit(28): 0 [usable: 0], DescribeAcls(29): 0 [usable: 0], CreateAcls(30): 0 [usable: 0], DeleteAcls(31): 0 [usable: 0], DescribeConfigs(32): 0 to 1 [usable: 1], AlterConfigs(33): 0 [usable: 0], AlterReplicaLogDirs(34): 0 [usable: 0], DescribeLogDirs(35): 0 [usable: 0], SaslAuthenticate(36): 0 [usable: 0], CreatePartitions(37): 0 [usable: 0], CreateDelegationToken(38): 0 [usable: 0], RenewDelegationToken(39): 0 [usable: 0], ExpireDelegationToken(40): 0 [usable: 0], DescribeDelegationToken(41): 0 [usable: 0], DeleteGroups(42): 0 [usable: 0])
11:47:10.716 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, groupId=registryStreamProcessor] Sending metadata request (type=MetadataRequest, topics=<ALL>) to node 127.0.0.1:53587 (id: -1 rack: null)
11:47:10.726 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-0] DEBUG kafka.request.logger - Completed request:RequestHeader(apiKey=METADATA, apiVersion=5, clientId=registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1-consumer, correlationId=2) -- {topics=null,allow_auto_topic_creation=true},response:{throttle_time_ms=0,brokers=[{node_id=1,host=127.0.0.1,port=53587,rack=null}],cluster_id=neH__3EVQ1uMDayV0tJpww,controller_id=1,topic_metadata=[{error_code=0,topic=MarketsRegistryTopic,is_internal=false,partition_metadata=[{error_code=0,partition=2,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=4,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=1,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=3,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=0,leader=1,replicas=[1],isr=[1],offline_replicas=[]}]},{error_code=0,topic=InputBettingOfferTopic,is_internal=false,partition_metadata=[{error_code=0,partition=2,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=4,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=1,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=3,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=0,leader=1,replicas=[1],isr=[1],offline_replicas=[]}]},{error_code=0,topic=EventsRegistryTopic,is_internal=false,partition_metadata=[{error_code=0,partition=2,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=4,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=1,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=3,leader=1,replicas=[1],isr=[1],offline_replicas=[]},{error_code=0,partition=0,leader=1,replicas=[1],isr=[1],offline_replicas=[]}]}]} from connection 127.0.0.1:53587-127.0.0.1:53635-6;totalTime:9.732,requestQueueTime:2.216,localTime:7.136,remoteTime:0.0,throttleTime:1.233,responseQueueTime:0.172,sendTime:0.209,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS,listener:PLAINTEXT
11:47:10.727 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] INFO  org.apache.kafka.clients.Metadata - Cluster ID: neH__3EVQ1uMDayV0tJpww
11:47:10.727 [registryStreamProcessor-6bea4a36-c783-4d58-9c2b-b4a330e0b287-StreamThread-1] DEBUG org.apache.kafka.clients.Metadata - Updated cluster metadata version 2 to Cluster(id = neH__3EVQ1uMDayV0tJpww, nodes = [127.0.0.1:53587 (id: 1 rack: null)], partitions = [Partition(topic = InputBettingOfferTopic, partition = 4, leader = 1, replicas = [1], isr = [1], offlineReplicas = []), Partition(topic = InputBettingOfferTopic, partition = 3, leader = 1, replicas = [1], isr = [1], offlineReplicas = []), Partition(topic = InputBettingOfferTopic, partition = 2, leader = 1, replicas = [1], isr = [1], offlineReplicas = []), Partition(topic = InputBettingOfferTopic, partition = 1, leader = 1, replicas = [1], isr = [1], offlineReplicas = []), Partition(topic = InputBettingOfferTopic, partition = 0, leader = 1, replicas = [1], isr = [1], offlineReplicas = [])])

**Comment by Crim** [comment]
So it should be compatible w/ Kafka Streams.  Your code sample looks correctly configured.  The only question I have is if Kafka Streams defaults to starting at the head/start of the topic, or tail/end of the topic on startup?

If it defaults to starting to consume from the tail/end of the topic, then it would make sense that you get nothing processed, because you produce data to the input topic, then start the stream which (maybe) starts at the end of the topic.

Try configuring the stream client to start from the head/start of the topic?

**Comment by SimoneCas** [comment]
HI, I have tried to move Stream application startup before message producer but I have the same result.

**Comment by Crim** [comment]
I added a test case to the code base.  Check it out in this PR here: https://github.com/salesforce/kafka-junit/pull/21

I think the piece you're missing is that stream processing is asynchronous.  You start the stream processor and then immediately look for results, but don't give it any time to do the actual processing.

Let me know if this helps

**Comment by SimoneCas** [comment]
Thank's, It's working fine!
