### ISSUE TITLE
Update to Kafka 2.x

### ISSUE THREAD

**Issue by bellemare** [salesforce/kafka-junit#26]
Update the support on this to Kafka 2.x (currently 1.0.2).

Doesn't look like the change would be too difficult. That being said, would it break Salesforce dependencies internally?

**Comment by bellemare** [comment]
Disregard. I see that there is support already.

**Comment by Crim** [comment]
Hey @bellemare please let me know if you run into any troubles running 3.0.1 against kafka 2.x.  Jenkins is configured to run the test suite against Kafka 2.0.0, so in theory, it should all work.

Thanks!
