### ISSUE TITLE
You have a failing test...

### ISSUE THREAD

**Issue by TristinDavis** [salesforce/kafka-junit#29]
It looks like you are missing 2 keystores in test/resources that you are using in your test when you generate the SSL Listener.  Other than that. Thank you for the lib.  Very easy to use!

-------------------------------------------------------------------------------
Test set: com.salesforce.kafka.test.KafkaTestClusterTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 95.623 s <<< FAILURE! - in com.salesforce.kafka.test.KafkaTestClusterTest
testRestartingCluster  Time elapsed: 27.585 s
testConsumingFromMultiBrokerClusterWhenBrokerIsStopped  Time elapsed: 31.111 s
testGetKafkaConnectString  Time elapsed: 15.577 s
testMultipleNodesInBroker  Time elapsed: 11.113 s
testGetKafkaBrokersBeforeClusterHasStarted  Time elapsed: 0.001 s
testGetKafkaBrokerByIdBeforeClusterStarted  Time elapsed: 0.002 s
testGetKafkaConnectStringBeforeClusterIsStarted  Time elapsed: 0.001 s
testCreateTopicAcrossMultipleBrokers  Time elapsed: 10.194 s
testCustomizedListeners{List}  Time elapsed: 10.227 s  <<< ERROR!
java.lang.NullPointerException
	at com.salesforce.kafka.test.KafkaTestClusterTest.provideListeners(KafkaTestClusterTest.java:425)

**Offending code**

```
 // Create SSL listener
final BrokerListener sslListener = new SslListener()
.withClientAuthRequired()
.withKeyStoreLocation(KafkaTestServer.class.getClassLoader().getResource("kafka.keystore.jks").getFile())
.withKeyStorePassword("password")            .withTrustStoreLocation(KafkaTestServer.class.getClassLoader().getResource("kafka.truststore.jks").getFile())
.withTrustStorePassword("password")
.withKeyPassword("password");

**Comment by Crim** [comment]
Hey @TristinDavis 

You can generate those missing keystores by running the [script/generateCertificatesForTests.sh](https://github.com/salesforce/kafka-junit/blob/master/script/generateCertificatesForTests.sh) script.

Unfortunately policy prohibits us from checking in these files to source control.  Likely I should update the project's README to make note of this.  

Thanks!
