### ISSUE TITLE
Error on starting up Kafka

### ISSUE THREAD

**Issue by jesusyapiko** [salesforce/kafka-junit#31]
Hi
I am getting these errors in the console when running a test with a very simple example:

```
10:47:40.333 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-0] DEBUG org.apache.kafka.common.network.Selector - [SocketServer brokerId=1] Connection with /127.0.0.1 disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:96)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
10:47:40.333 [kafka-network-thread-1-ListenerName(PLAINTEXT)-PLAINTEXT-1] DEBUG org.apache.kafka.common.network.Selector - [SocketServer brokerId=1] Connection with /127.0.0.1 disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:96)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
	at kafka.network.Processor.poll(SocketServer.scala:689)
	at kafka.network.Processor.run(SocketServer.scala:594)
	at java.lang.Thread.run(Thread.java:748)
```

I am using the following versions:

- <**kafka**.version>**2.1.1**</kafka.version>
- <kafka.**junit4**.version>**3.1.0**</kafka.junit4.version>

And this is the code:
```
    @ClassRule
    public static final SharedKafkaTestResource sharedKafkaTestResource = new SharedKafkaTestResource();

    @Test
    public void kafkaTest() {

        long timeout = 1000L * 60L * 5L;
        long start = System.currentTimeMillis();

        while (System.currentTimeMillis() - start <= timeout) {

        }

        System.out.println("Exiting test");
    }
```

However, I tested Kafka directly from the console (**kafka-console-consumer.sh** and **kafka-console-producer.sh**) and it seems to be working properly.

**Comment by Crim** [comment]
I'm not sure that this library has been validated against Kafka 2.1.x yet.   But from reviewing the log line you pasted it looks to be a DEBUG level log, and not raised as a WARNING or ERROR.

Are you seeing issues when you run test cases against the internal kafka server?

**Comment by jesusyapiko** [comment]
No, Kafka server is working fine but I do not see those traces when running it in another standalone installation that I have (not even in DEBUG level).

I also tried it with Kafka 2.0.0 version and got the same result.

I am not sure but the error might has to do with the **KafkaAdminClient** because those traces go always after this one:

`09:51:59.715 [kafka-admin-client-thread | test-consumer-id] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient - [AdminClient clientId=test-consumer-id] Exiting AdminClientRunnable thread.`

I do not know why it is using **KafkaAdminClient** (and its **test-consumer-id**) as I do not see it in the logs of the standalone Kafka installation.

**Comment by Crim** [comment]
The AdminClient is used during [startup here](https://github.com/salesforce/kafka-junit/blob/master/kafka-junit-core/src/main/java/com/salesforce/kafka/test/KafkaTestCluster.java#L168-L169) to block until the cluster is up and ready to serve requests.

**Comment by jesusyapiko** [comment]
Thank you Crim.

In the end, we ignored that error as does not affect its functioning.

However, with respect to what you mentioned about knowing whether the server is up or down, I did not find a reliable method to perform that check.

I tried this to check that the server is up:
`sharedKafkaTestResource.getKafkaTestUtils().waitForBrokerToComeOnLine(1, 10, TimeUnit.SECONDS);`
but after passing that line the broker was not listening yet.

And then, I tried this to check that the server is down:
```  
    @AfterClass
    public static void after() throws InterruptedException {
        while (sharedKafkaTestResource.getKafkaTestUtils().describeClusterNodes().size() > 0) {
            Thread.sleep(500L);
            System.out.println("Waiting Kafka to be down...");
        }
        System.out.println("Kafka is down");
        consumer.stop();
        producer.close();
    }
```

**Comment by MatanRubin** [comment]
@Crim, any clue as to why this happens even when `waitForBrokerToComeOnLine` is used?
I'm seeing the exact same issue: when `waitForBrokerToComeOnLine` returns I see the broker is not listening yet. I need to add a few seconds of sleep for things to work properly...

**Comment by Crim** [comment]
Hi @MatanRubin , Are you able to post a code snippet that shows how you're setting up the test case, and where you're needing to add the sleep statement?

**Comment by MatanRubin** [comment]
@Crim, feel free to ignore my last comment. I saw many exceptions in the test log and thought it meant the server is not ready, but then I re-read this thread and understood that these exceptions are shown in DEBUG level and are not an actual issue.

I created a small test just to make sure everything is working properly - and it does. Posting the test here for posterity.

```java
public class KafkaTest {

    @ClassRule
    public static final SharedKafkaTestResource sharedKafkaTestResource = new SharedKafkaTestResource();

    @Test
    public void testSendReceive() throws TimeoutException {
        KafkaTestUtils testUtils = sharedKafkaTestResource.getKafkaTestUtils();

        // wait for broker to start listening
        testUtils.waitForBrokerToComeOnLine(1, 10, TimeUnit.SECONDS);

        String topicName = "testTopic";
        testUtils.createTopic(topicName, 1, (short) 1);

        KafkaProducer<String, String> producer =
                testUtils.getKafkaProducer(StringSerializer.class, StringSerializer.class);
        producer.send(new ProducerRecord<>(topicName, null, "value"));

        Properties properties = new Properties();
        properties.put(ConsumerConfig.GROUP_ID_CONFIG, "group-id");
        KafkaConsumer<String, String> consumer =
                testUtils.getKafkaConsumer(StringDeserializer.class, StringDeserializer.class, properties);
        consumer.subscribe(Collections.singletonList(topicName));
        ConsumerRecords<String, String> records = consumer.poll(Duration.ofSeconds(10));
        for (ConsumerRecord<String, String> record : records) {
            Assert.assertEquals("value", record.value());
        }
    }
}
```

**Comment by Crim** [comment]
Thanks for following up!  Just a FYI -- In your test case above these lines should **not** been needed, as that is called automatically as part of the initialization of the ClassRule :)

```java
// wait for broker to start listening
testUtils.waitForBrokerToComeOnLine(1, 10, TimeUnit.SECONDS);
```

**Comment by MatanRubin** [comment]
cool, thanks for letting me know!
