### ISSUE TITLE
Transactional Support

### ISSUE THREAD

**Issue by chrisccoy** [salesforce/kafka-junit#4]
This appears to be a great submission, thank you. I am implementing something with kafka using pure Java and was getting frustrated with solutions that were opinionated: Scala or Spring. I love how easy this is to use and implement with a single dependency.

I might be getting greedy here, but for my testing it would be great to see the ability to support transactions. (requires 2 replicas, I think) I am working around my test cases, but it's not pretty:

`        if (!inTest())
        {
            producer.beginTransaction();
        }
`

Aside from that 👍

**Comment by Crim** [comment]
Can you post (in a gist or elsewhere) a simplified example test case showing what you're trying to do and how its failing?  I think that would help clarify your request for me.

Thanks!

**Comment by chrisccoy** [comment]
Please see the following [gist](https://gist.github.com/chrisccoy/2670b184e24274607627490c5f49c0d3)

I am trying to unit test "exactly-once" semantics, which requires transactions. I commented out all of the code that requires transactions with "TODO" to demonstrate what I am trying to accomplish. Like I said above, I might be getting too greedy, but would be really nice if this could be achieved.

If we remove the code that is transactional in nature the following will result, because we are running as a single node:
```
ERROR [Replica Manager on Broker 1]: Error processing append operation on partition __transaction_state-22 (kafka.server.ReplicaManager:105) 
org.apache.kafka.common.errors.NotEnoughReplicasException: Number of insync replicas for partition __transaction_state-22 is [1], below required minimum [2]
INFO [Transaction
```

**Comment by Crim** [comment]
Thanks, I'll poke around on this.  I believe we may just need to set this property either on the server configuration, or maybe the consumer.  

`transaction.state.log.min.isr=1`

**Comment by Crim** [comment]
OK, yea I've gotten your test case to pass with that modification.  Let me work out how to add this test case in without breaking it for older kafka versions.

**Comment by Crim** [comment]
I'll be cutting release 2.2.0 today which will include the fix for this issue. 

Thanks for bringing it to our attention! :)

**Comment by chrisccoy** [comment]
👍 Awesome, thanks!
