### ISSUE TITLE
Is it possible to run against mock schema registry?

### ISSUE THREAD

**Issue by jcchavezs** [salesforce/kafka-junit#44]
Kafka Streams Test Utils provides support for mock schema registry. Is it possible to do so with this library?

**Comment by Crim** [comment]
I may have misunderstood your question, but its my understanding that SchemaRegistry runs outside of a Kafka server or cluster.  If you have a MockSchemaRegistry instance (such as [this](https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java)) you should be able to configure your KafkaClient instances to use it without any issue.

**Comment by jcchavezs** [comment]
So in Kafka Streams Test Utils, if you use the pseudo protocol `mock` you
don't need to use the MockSchemaRegistryClient. See
https://github.com/timtebeek/topology-test-driver-avro/pull/4/files

José Carlos Chávez


tor. 16. apr. 2020 kl. 07:54 skrev Steviep <notifications@github.com>:

**Comment by jcchavezs** [comment]
nvm, it looks like that is handled by the SpecificAvroSerializer/Deserializer. Maybe worth to add to documentation?
