### ISSUE TITLE
Kafka 2.5.x support

### ISSUE THREAD

**Issue by pontello** [salesforce/kafka-junit#45]
Any plans for supporting kafka 2.5.x?

**Comment by Crim** [comment]
It may just work if you include the correct 2.5.x dependencies in your project.  I've setup a branch that will run the test suite against the 2.5.x and 2.6.x version once they've been replicated out to the maven repositories.

**Comment by Crim** [comment]
Validated against kafka versions 2.5.x and 2.6.x.  Everything seems to work as expected.  I updated the documentation to reflect this.

I released version `3.2.2` of the library with *official* support, but previous versions should work without issues.

Thanks!
