### ISSUE TITLE
Wrong code example in README.md Kafka-JUnit4/5 (SASL_PLAINTEXT)

### ISSUE THREAD

**Issue by pelagos91** [salesforce/kafka-junit#48]
Hi, I noticed that SASL_PLAINTEXT section of kafka-junit4 and kafka-junit5 readme.md file, contains an apparently wrong code example. In particular there are references to methods for SSL options setting that are not implemented in the SaslPlainListener.

**Comment by Crim** [comment]
Thanks for pointing that out!  I've updated the READMEs to be correct.

Thanks again!
